# -*- coding: utf-8 -*-
"""Flute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11iPLpFDs9g6-PVym0v-kXZts2DJc4Tb9
"""

pip install mido

pip install pyserial

import mido
import time
import serial

# Updated flute patterns as per your specifications
note_map = {
    # C3 to B3 (MIDI notes 48 to 59)
    48: {"key": "C3", "keyboard_servo": 1, "keyboard_direction": 0, "flute_pattern": "000222"},  # C3
    49: {"key": "C#3", "keyboard_servo": 5, "keyboard_direction": 1, "flute_pattern": "000122"},  # C#3
    50: {"key": "D3", "keyboard_servo": 1, "keyboard_direction": 0, "flute_pattern": "000022"},  # D3
    51: {"key": "D#3", "keyboard_servo": 5, "keyboard_direction": 1, "flute_pattern": "000012"},  # D#3
    52: {"key": "E3", "keyboard_servo": 2, "keyboard_direction": 0, "flute_pattern": "000002"},  # E3
    53: {"key": "F3", "keyboard_servo": 2, "keyboard_direction": 1, "flute_pattern": "000001"},  # F3
    54: {"key": "F#3", "keyboard_servo": 6, "keyboard_direction": 0, "flute_pattern": "000000"},  # F#3
    55: {"key": "G3", "keyboard_servo": 3, "keyboard_direction": 1, "flute_pattern": "222222"},  # G3
    56: {"key": "G#3", "keyboard_servo": 6, "keyboard_direction": 0, "flute_pattern": "122222"},  # G#3
    57: {"key": "A3", "keyboard_servo": 3, "keyboard_direction": 1, "flute_pattern": "022222"},  # A3
    58: {"key": "A#3", "keyboard_servo": 4, "keyboard_direction": 0, "flute_pattern": "012222"},  # A#3
    59: {"key": "B3", "keyboard_servo": 4, "keyboard_direction": 1, "flute_pattern": "002222"},  # B3

    # C4 to B4 (MIDI notes 60 to 71)
    60: {"key": "C4", "keyboard_servo": 7, "keyboard_direction": 0, "flute_pattern": "000222"},  # C4
    61: {"key": "C#4", "keyboard_servo": 11, "keyboard_direction": 0, "flute_pattern": "000122"},  # C#4
    62: {"key": "D4", "keyboard_servo": 7, "keyboard_direction": 1, "flute_pattern": "000022"},  # D4
    63: {"key": "D#4", "keyboard_servo": 11, "keyboard_direction": 1, "flute_pattern": "000012"},  # D#4
    64: {"key": "E4", "keyboard_servo": 8, "keyboard_direction": 0, "flute_pattern": "000002"},  # E4
    65: {"key": "F4", "keyboard_servo": 8, "keyboard_direction": 1, "flute_pattern": "000001"},  # F4
    66: {"key": "F#4", "keyboard_servo": 12, "keyboard_direction": 0, "flute_pattern": "000000"},  # F#4
    67: {"key": "G4", "keyboard_servo": 9, "keyboard_direction": 0, "flute_pattern": "222222"},  # G4
    68: {"key": "G#4", "keyboard_servo": 12, "keyboard_direction": 1, "flute_pattern": "122222"},  # G#4
    69: {"key": "A4", "keyboard_servo": 9, "keyboard_direction": 1, "flute_pattern": "022222"},  # A4
    70: {"key": "A#4", "keyboard_servo": 10, "keyboard_direction": 0, "flute_pattern": "012222"},  # A#4
    71: {"key": "B4", "keyboard_servo": 10, "keyboard_direction": 1, "flute_pattern": "002222"},  # B4

    # C5 to B5 (MIDI notes 72 to 83)
    72: {"key": "C5", "keyboard_servo": 13, "keyboard_direction": 0, "flute_pattern": "000222"},  # C5
    73: {"key": "C#5", "keyboard_servo": 17, "keyboard_direction": 1, "flute_pattern": "000122"},  # C#5
    74: {"key": "D5", "keyboard_servo": 13, "keyboard_direction": 0, "flute_pattern": "000022"},  # D5
    75: {"key": "D#5", "keyboard_servo": 17, "keyboard_direction": 1, "flute_pattern": "000012"},  # D#5
    76: {"key": "E5", "keyboard_servo": 14, "keyboard_direction": 0, "flute_pattern": "000002"},  # E5
    77: {"key": "F5", "keyboard_servo": 14, "keyboard_direction": 1, "flute_pattern": "000001"},  # F5
    78: {"key": "F#5", "keyboard_servo": 18, "keyboard_direction": 0, "flute_pattern": "000000"},  # F#5
    79: {"key": "G5", "keyboard_servo": 15, "keyboard_direction": 1, "flute_pattern": "222222"},  # G5
    80: {"key": "G#5", "keyboard_servo": 18, "keyboard_direction": 0, "flute_pattern": "122222"},  # G#5
    81: {"key": "A5", "keyboard_servo": 15, "keyboard_direction": 1, "flute_pattern": "022222"},  # A5
    82: {"key": "A#5", "keyboard_servo": 16, "keyboard_direction": 0, "flute_pattern": "012222"},  # A#5
    83: {"key": "B5", "keyboard_servo": 16, "keyboard_direction": 1, "flute_pattern": "002222"},  # B5
}

# Function to calculate delay based on velocity
def calculate_delay(velocity):
    min_delay = 100  # Minimum delay in ms
    max_delay = 500  # Maximum delay in ms
    delay = min_delay + (max_delay - min_delay) * (127 - velocity) / 127
    return int(delay)

# Function to play MIDI file and send servo instructions to Arduino
def play_midi_from_file(midi_file_path):
    arduino = serial.Serial(port='/dev/tty.usbmodem21301', baudrate=9600, timeout=0.1)  # Update with your Arduino port
    midi_file = mido.MidiFile(midi_file_path)

    for msg in midi_file.play():
        if msg.type == 'note_on' or msg.type == 'note_off':
            note = msg.note
            velocity = msg.velocity

            if note in note_map:
                keyboard_note = note_map[note]["key"]
                servo_no = note_map[note]["keyboard_servo"]
                action = "pressed" if msg.type == 'note_on' else "released"

                # Determine servo direction
                servo_direction = note_map[note]["keyboard_direction"]
                if msg.type == 'note_off':
                    servo_direction = 1 - servo_direction  # Reverse direction for release

                # Get flute pattern
                flute_pattern = note_map[note]["flute_pattern"]

                # Combine output into a 9-digit code
                output = f"{servo_no:02}{servo_direction}{flute_pattern}"
                print(f"Note {keyboard_note} {action}: Output Code = {output}")

                # Send data to Arduino
                arduino.write((output + "\n").encode())

                # Simulate the action with a delay
                time.sleep(calculate_delay(velocity) / 1000.0)

    arduino.close()

# Example usage
play_midi_from_file("/path/to/your/midi/file.mid")