# -*- coding: utf-8 -*-
"""AUTOMATED KEYBOARD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WlOAUP7xPykyJw0wP-xOmqaN2IKqRwg
"""

pip install mido

pip install pyserial

import mido
import time
import serial

# Mapping MIDI notes to servos based on the new specification
note_map = {
    48: {"key": "C3", "servo": 1, "servo_direction": 0},  # B#4
    50: {"key": "D3", "servo": 1, "servo_direction": 1},  # B#4
    52: {"key": "E3", "servo": 2, "servo_direction": 0},  # B#4
    53: {"key": "F3", "servo": 2, "servo_direction": 1},  # B#4
    55: {"key": "G3", "servo": 3, "servo_direction": 0},  # B#4
    57: {"key": "A3", "servo": 3, "servo_direction": 1},  # B#4
    59: {"key": "B3", "servo": 4, "servo_direction": 0},  # B#4
    49: {"key": "C#3", "servo": 5, "servo_direction": 0},  # B#4
    51: {"key": "D#3", "servo": 5, "servo_direction": 1},  # B#4
    54: {"key": "F#3", "servo": 6, "servo_direction": 0},  # B#4
    56: {"key": "G#3", "servo": 6, "servo_direction": 1},  # B#4
    58: {"key": "A#3", "servo": 4, "servo_direction": 0},  # B#4
    60: {"key": "C4", "servo": 7, "servo_direction": 0},  # C4
    62: {"key": "D4", "servo": 7, "servo_direction": 1},  # D4
    64: {"key": "E4", "servo": 8, "servo_direction": 0},  # E4
    65: {"key": "F4", "servo": 8, "servo_direction": 1},  # F4
    67: {"key": "G4", "servo": 9, "servo_direction": 0},  # G4
    69: {"key": "A4", "servo": 9, "servo_direction": 1},  # A4
    61: {"key": "C#4", "servo":11, "servo_direction": 0},  # C#4
    63: {"key": "D#4", "servo":11, "servo_direction": 1},  # D#4
    66: {"key": "F#4", "servo":12, "servo_direction": 0},  # F#4
    68: {"key": "G#4", "servo": 12, "servo_direction": 1},  # G#4
    71: {"key": "B4", "servo": 10, "servo_direction": 1},  # B4
    70: {"key": "A#4", "servo":10, "servo_direction": 0},  # B#4
    72: {"key": "C5", "servo": 13, "servo_direction": 0},  # B#4
    74 : {"key": "D5", "servo":13, "servo_direction": 1},  # B#4
    76 : {"key": "E5", "servo":14, "servo_direction": 0},  # B#4
    77 : {"key": "F5", "servo":14, "servo_direction": 1},  # B#4
    79: {"key": "G5", "servo": 15, "servo_direction": 0},  # B#4
    81 : {"key": "A5", "servo": 15, "servo_direction": 1},  # B#4
    83 : {"key": "B5", "servo": 16, "servo_direction": 0},  # B#4
    84 : {"key": "C6", "servo": 19 , "servo_direction": 1},
    82 : {"key": "C#5", "servo":17, "servo_direction": 1},  # B#4
    75 : {"key": "D#5", "servo":17, "servo_direction": 1},  # B#4
    78 : {"key": "F#5", "servo":18, "servo_direction": 1},  # B#4
    80 : {"key": "G#5", "servo":18, "servo_direction": 1},  # B#4
    82 : {"key": "A#5", "servo":16, "servo_direction": 1},  # B#4
}


# Function to calculate delay based on velocity
def calculate_delay(velocity):
    min_delay = 100  # Minimum delay in ms
    max_delay = 500  # Maximum delay in ms
    delay = min_delay + (max_delay - min_delay) * (127 - velocity) / 127
    return int(delay)

# Function to play MIDI file and send servo instructions to Arduino
def play_midi_from_file(midi_file_path):
    # Open serial connection to Arduino
    arduino = serial.Serial(port= 'COM4', baudrate=9600, timeout=1)  # Replace 'COM3' with your Arduino port

    midi_file = mido.MidiFile(midi_file_path)

    for msg in midi_file.play():
        if msg.type == 'note_on' or msg.type == 'note_off':
            note = msg.note
            velocity = msg.velocity

            if note in note_map:
                keyboard_note = note_map[note]["key"]
                servo_no = note_map[note]["servo"]
                action = "pressed" if msg.type == 'note_on' else "released"

                # Determine servo direction
                servo_direction = note_map[note]["servo_direction"]
                if msg.type == 'note_off':
                    servo_direction = 1 - servo_direction  # Reverse direction for release

                # Calculate delay
                delay = calculate_delay(velocity)

                # Format output
                output = f"{servo_no:02}{delay:04}{servo_direction}"
                print(f"Note {keyboard_note} {action}: Output Code = {output}")

                # Send data to Arduino
                arduino.write((output + "\n").encode())  # Send output with a newline character

                # Simulate the action with a delay
                time.sleep(delay / 1000.0)

    # Close the serial connection
    arduino.close()

# Example usage
play_midi_from_file(r"PATH")

